FROM python:3.11-slim-bookworm

RUN apt-get update \
 && apt-get upgrade -yqq \
 && apt-get install make git rsync zstd curl neovim psmisc -y

COPY pyproject.toml .
RUN pip install --upgrade pip \
 && pip install toml \
 && python -c "import toml; p = toml.load('pyproject.toml')['project']; print('\n'.join(p['dependencies'])); print('\n'.join(p['optional-dependencies']['dev']))" \
  | xargs pip install --use-deprecated=legacy-resolver \
 && rm pyproject.toml

RUN useradd sax -u 1000 -s /bin/bash

USER sax
WORKDIR /home/sax

ADD . /home/sax

CMD ["/bin/bash"]
