site_name: sax
repo_url: https://github.com/flaport/sax
site_url: https://flaport.github.io/sax
site_description: Autograd and XLA for S-parameters
site_author: Floris Laporte
repo_name: flaport/sax
copyright: Copyright © 2025, Floris Laporte, Apache-2.0

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system default
      primary: blue
      accent: deep purple
  features:
    - navigation.footer
  search: true

nav:
  - home: index.md
  - examples:
      - quick start: nbs/examples/01_quick_start.md
      - all pass: nbs/examples/02_all_pass_filter.md
      - circuit from yaml: nbs/examples/03_circuit_from_yaml.md
      - multimode: nbs/examples/04_multimode_simulations.md
      - thin film:  nbs/examples/05_thinfilm.md
      - additive: nbs/examples/06_additive_backend.md
      - layout aware: nbs/examples/07_layout_aware.md
      - sparse (coo): nbs/examples/08_sparse_coo.md
      - forward only:  nbs/examples/09_forward_only_backend.md
      - neff dispersion: nbs/examples/10_wavelength_dependent_neff.md
      - hierarchical circuits: nbs/examples/11_hierarchical_circuits.md
      - surface models: nbs/examples/12_surface_models.md
  - internals:
      - backends: nbs/internals/03_backends.md
      - circuit: nbs/internals/02_circuit.md
      - models: nbs/internals/01_models.md
      - all models: nbs/internals/04_all_models.md
  - api reference:
      - sax: api.md
      - sax.fit: fit.md
      - models: models.md
  - changelog: changelog.md

extra_css:
  - assets/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - autorefs
  - mkdocs_matplotlib
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.jax.dev/en/latest/objects.inv
            - https://docs.kidger.site/jaxtyping/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://docs.xarray.dev/en/stable/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://python-markdown.github.io/objects.inv
            - https://scipy.github.io/devdocs/objects.inv
            - https://typing.readthedocs.io/en/latest/objects.inv
            - https://www.mkdocs.org/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            docstring_style: google
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            line_length: 88
            merge_init_into_class: true
            separate_signature: true
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

hooks:
  - docs/hooks.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flaport
