# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://flaport.github.io/sax/"

git_url = "https://github.com/flaport/sax/tree/master/"

def custom_doc_links(name): return None
