# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_backends.ipynb (unless otherwise specified).


from __future__ import annotations


__all__ = ['circuit_backends']

# Internal Cell
#nbdev_comment from __future__ import annotations

try:
    import jax
    import jax.numpy as jnp
    JAX_AVAILABLE = True
except ImportError:
    import numpy as jnp
    JAX_AVAILABLE = False

try:
    import klujax
    KLUJAX_AVAILABLE = True
except ImportError:
    KLUJAX_AVAILABLE = False

from .default import analyze_circuit, evaluate_circuit
from .additive import analyze_circuit_additive, evaluate_circuit_additive

if JAX_AVAILABLE and KLUJAX_AVAILABLE:
    from .klu import analyze_circuit_klu, evaluate_circuit_klu

# Cell

circuit_backends = {
    "default": (analyze_circuit, evaluate_circuit),
    "additive": (analyze_circuit_additive, evaluate_circuit_additive),
}

if JAX_AVAILABLE and KLUJAX_AVAILABLE:
    circuit_backends["klu"] = (analyze_circuit_klu, evaluate_circuit_klu)