name: Docs
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  run:
    name: Run Notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Install Just
        uses: taiki-e/install-action@just
      - name: Run notebooks
        run: just dev nbrun
      - name: Upload artifacts [nbs]
        uses: actions/upload-artifact@v4
        with:
          name: nbs
          path: ./nbs

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts [nbs]
        uses: actions/download-artifact@v4
        with:
          name: nbs
          path: ./nbs
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Install Just
        uses: taiki-e/install-action@just
      - name: Build docs
        run: just dev nbdocs docs
      - name: Upload artifact [site]
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./site

  pages:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs:
      - docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
