name: Test documentation

on:
  pull_request:
  push:
  schedule:
      - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install pandoc
        make install
    - name: Test documentation
      run: |
        cd docs
        make html
