name: ReleaseDrafter
on:
  push:
    branches:
      - main
  pull_request:
    types: [edited, opened, reopened, synchronize, unlabeled, labeled]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  require_label:
    if: github.event.pull_request
    needs: update_release_draft
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: 'breaking, feat, bug, maint, github_actions, docs, deps'
          add_comment: true
